# Generated by Django 4.0.6 on 2022-09-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldetail', '0008_alter_articles_stock'),
        ('docuclient', '0004_remove_facture_date_updated'),
        ('users', '0002_profile_is_staff_profile_last_connect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='administrationClients',
            field=models.ManyToManyField(blank=True, to='alldetail.administrationclient'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bonLivraisons',
            field=models.ManyToManyField(blank=True, to='docuclient.bonlivraison'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='categorys',
            field=models.ManyToManyField(blank=True, to='alldetail.category'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='clientParticuliers',
            field=models.ManyToManyField(blank=True, to='alldetail.clientparticulier'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='conventionEntrepriseClients',
            field=models.ManyToManyField(blank=True, to='alldetail.conventionentrepriseclient'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='devisClients',
            field=models.ManyToManyField(blank=True, to='docuclient.devisclient'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='entrepriseClients',
            field=models.ManyToManyField(blank=True, to='alldetail.entrepriseclient'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='factures',
            field=models.ManyToManyField(blank=True, to='docuclient.facture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='products',
            field=models.ManyToManyField(blank=True, to='alldetail.product'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ravites',
            field=models.ManyToManyField(blank=True, to='docuclient.ravite'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shops',
            field=models.ManyToManyField(blank=True, to='alldetail.shop'),
        ),
    ]
