# Generated by Django 4.0.6 on 2022-09-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldetail', '0009_allclientdata_remove_administrationclient_author_and_more'),
        ('users', '0003_alter_profile_administrationclients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='administrationClients',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='clientParticuliers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='conventionEntrepriseClients',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='entrepriseClients',
        ),
        migrations.AddField(
            model_name='profile',
            name='ALLClientData',
            field=models.ManyToManyField(blank=True, to='alldetail.allclientdata'),
        ),
    ]
