# Generated by Django 4.0.6 on 2022-09-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_order_cart_facturation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(help_text='Html2canvas screenshot', upload_to='img/screenshots/')),
            ],
        ),
    ]
