# Generated by Django 4.0.6 on 2022-09-01 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docuclient', '0004_remove_facture_date_updated'),
        ('alldetail', '0002_alter_administrationclient_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articles',
            name='facture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facture_article', to='docuclient.facture'),
        ),
    ]
