# Generated by Django 4.0.6 on 2022-09-02 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docuclient', '0004_remove_facture_date_updated'),
        ('alldetail', '0004_alter_articles_active_alter_articles_facture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='facture',
        ),
        migrations.AddField(
            model_name='articles',
            name='facture',
            field=models.ManyToManyField(null=True, related_name='facture_article', to='docuclient.facture'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='quantite_client',
            field=models.FloatField(blank=True, default=1.0, null=True, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
