# Generated by Django 4.0.6 on 2022-09-02 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('docuclient', '0004_remove_facture_date_updated'),
        ('alldetail', '0005_remove_articles_facture_articles_facture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='articles',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='facture',
            field=models.ManyToManyField(related_name='facture_article', to='docuclient.facture'),
        ),
        migrations.AddIndex(
            model_name='articles',
            index=models.Index(fields=['content_type', 'object_id'], name='alldetail_a_content_b70924_idx'),
        ),
    ]
