# Generated by Django 4.0.6 on 2022-09-03 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldetail', '0007_remove_articles_facture_articles_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='stock',
            field=models.FloatField(blank=True, default=1.0, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
