# Generated by Django 4.0.6 on 2022-09-05 02:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('alldetail', '0008_alter_articles_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALLClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_payment', models.CharField(blank=True, choices=[('A échéance', 'A échéance'), ('Définis dans le contrat', 'Définis dans le contrat'), ('Journalier, hebdomadaire, mensuel', 'Journalier, hebdomadaire, mensuel')], max_length=200, null=True)),
                ('nation_choices', models.CharField(blank=True, choices=[('National', 'National'), ('International', 'International')], max_length=100, null=True)),
                ('document_choices', models.CharField(blank=True, choices=[('Bon de livraison', 'Bon de livraison'), ('Devis', 'Devis'), ('Facture', 'Facture')], max_length=100, null=True)),
                ('client_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_Code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email_Address', models.EmailField(blank=True, max_length=200, null=True)),
                ('partenary_code', models.CharField(blank=True, max_length=200, null=True)),
                ('taxe_TPS', models.FloatField(blank=True, null=True)),
                ('taxe_CSS', models.FloatField(blank=True, null=True)),
                ('remise', models.FloatField(blank=True, null=True)),
                ('livraison', models.CharField(blank=True, max_length=200, null=True)),
                ('modalite_paiement', models.FloatField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='administrationclient',
            name='author',
        ),
        migrations.RemoveField(
            model_name='administrationclient',
            name='bonlivraison_administration',
        ),
        migrations.RemoveField(
            model_name='administrationclient',
            name='devisadministrationClient',
        ),
        migrations.RemoveField(
            model_name='administrationclient',
            name='facture',
        ),
        migrations.RemoveField(
            model_name='clientparticulier',
            name='author',
        ),
        migrations.RemoveField(
            model_name='clientparticulier',
            name='bonlivraison_client_particulier',
        ),
        migrations.RemoveField(
            model_name='clientparticulier',
            name='devisClient_particulier',
        ),
        migrations.RemoveField(
            model_name='clientparticulier',
            name='facture',
        ),
        migrations.RemoveField(
            model_name='conventionentrepriseclient',
            name='author',
        ),
        migrations.RemoveField(
            model_name='conventionentrepriseclient',
            name='bonlivraison_convention_entreprise',
        ),
        migrations.RemoveField(
            model_name='conventionentrepriseclient',
            name='devisconventionentrepriseClient',
        ),
        migrations.RemoveField(
            model_name='conventionentrepriseclient',
            name='facture',
        ),
        migrations.RemoveField(
            model_name='entrepriseclient',
            name='author',
        ),
        migrations.RemoveField(
            model_name='entrepriseclient',
            name='bonlivraison_entreprise',
        ),
        migrations.RemoveField(
            model_name='entrepriseclient',
            name='devisentrepriseClient',
        ),
        migrations.RemoveField(
            model_name='entrepriseclient',
            name='facture',
        ),
    ]
