# Generated by Django 4.0.6 on 2022-09-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldetail', '0010_delete_administrationclient_delete_clientparticulier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allclientdata',
            name='wait_money',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allclientdata',
            name='type_payment',
            field=models.CharField(blank=True, choices=[('A échéance', 'A échéance'), ('Définis dans le contrat', 'Définis dans le contrat'), ('Journalier, hebdomadaire, mensuel', 'Journalier, hebdomadaire, mensuel'), ('Cash', 'Cash')], max_length=200, null=True),
        ),
    ]
