# Generated by Django 4.0.6 on 2022-09-01 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docuclient', '0003_alter_bonlivraison_author_alter_devisclient_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='date_updated',
        ),
    ]
